name: Docker CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Construir imagen Docker
        run: docker build -t mi-app-node .
        
      - name: Ejecutar contenedor
        run: docker run mi-app-node